name: Build and Deploy LaTeX document

on:
  push:
    branches:
      - main
    paths:
      - '**/*.tex'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex  # Sostituisci con il tuo file .tex principale

      - name: Upload PDF file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: main.pdf

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: .  # Puoi specificare una sottocartella se necessario, ad esempio "./pdfs"
          publish_branch: main  # Utilizza il branch corrente, senza bisogno di gh-pages
          personal_token: ${{ secrets.GITHUB_TOKEN }}
